--- #YAML:1.0
name:                CMS-JoomlaToDrupal
version:             0.05
abstract:            migrate legacy Joomla content to Drupal 
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    DateTime:                      0
    DBI:                           0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Hugh Esco <hesco@campaignfoundations.com>
